name: build-android-librustdesk

on:
  workflow_dispatch:
  push:
    paths:
      - "**"
      - .github/workflows/build-android-librustdesk.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,x86_64-linux-android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Android SDK + NDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: |
          sdkmanager --install "ndk;26.3.11579264"
          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/26.3.11579264" >> $GITHUB_ENV

      - name: Install cargo-ndk
        run: cargo install cargo-ndk --locked

      - name: Build librustdesk.so (arm64-v8a, x86_64)
        run: |
          mkdir -p  artifacts/jniLibs
          cargo ndk \
            -t arm64-v8a \
            -t x86_64 \
            -o  artifacts/jniLibs \
            build \
            --release \
            --lib \
            --features flutter \
            --target-dir target_android

      - name: Upload artifacts (jniLibs)
        uses: actions/upload-artifact@v4
        with:
          name: librustdesk-jniLibs
          path: artifacts/jniLibs
